language: android
android:
  components:
    - build-tools-19.0.3
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'
before_script: travis/before_script.sh
script: travis/script.sh
deploy:
  provider: releases
  api_key:
    secure: "Wn0Nfig9ju5Mzysx3aZR/QaRw5kOc4XxBuBj7Xw3cV34voOhB3tBqRPDol1ZI9ejdIjicBCosKQnW5ji80zkhQgKZ3c+PuSCUM0LniOEv3UDelabJC8WUHv9exm4kKNfV8pBYaBGnVVPtIZQZPwUpwvx0VmfjR69zvhcvxJhygY="
  file: Gameeso-Android-SDK.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: Gameeso/openkit-android